language: node_js
node_js:
  - "8.0.0"
  - "9.2.0"
  - "10.0.0"
install:
  - npm install
before_script:
  - npm run build
  - npm run build:test
script:
  - npm run test
after_script:
  - npm run coverage
  - npm run coveralls