language: node_js

# branches to build
branches:
  # whitelist
  only:
    - master
    - /version*/

node_js:
  - "10.0.0"
  - "11.1.0"
  - "12.0.0"
install:
  - npm install
before_script:
  - npm run build
  - npm run extract-api
  - npm run pack
script:
  - npm run test:pkg
  - npm run test:100
